# Generated by Django 4.2 on 2023-04-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=255)),
                ('eemail', models.EmailField(max_length=254)),
                ('esal', models.IntegerField()),
                ('eadd', models.CharField(max_length=200)),
            ],
        ),
    ]
