# Generated by Django 4.1.7 on 2023-03-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Emp_image',
            field=models.ImageField(default=0, upload_to='images'),
            preserve_default=False,
        ),
    ]
