# Generated by Django 4.1.7 on 2023-03-28 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_employee_emp_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Emp_image',
        ),
    ]
