# Generated by Django 4.1.7 on 2023-03-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0003_remove_employee_emp_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='EmpDesc',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='EmpEmail',
            field=models.EmailField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='EmpName',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='EmpNum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='EmpSal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
