# Generated by Django 2.1.7 on 2023-04-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='uname',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
