# Generated by Django 2.1.7 on 2023-04-10 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0002_registration_uname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='tokem',
            new_name='token',
        ),
    ]
