# Generated by Django 4.1.7 on 2023-03-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelloapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveller_det',
            name='tr_aadar',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='traveller_det',
            name='tr_age',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='traveller_det',
            name='tr_gender',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='traveller_det',
            name='tr_image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='traveller_det',
            name='tr_name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
