# Generated by Django 4.1.7 on 2023-03-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelloapp', '0002_alter_traveller_det_tr_aadar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveller_det',
            name='tr_phnum',
            field=models.IntegerField(blank=True),
        ),
    ]
