# Generated by Django 4.1.7 on 2023-03-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelloapp', '0009_alter_traveller_det_tr_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveller_det',
            name='tr_phnum',
            field=models.IntegerField(blank=True, default=0, max_length=12, verbose_name='tr_phnum'),
        ),
    ]
