# Generated by Django 4.1.7 on 2023-03-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelloapp', '0010_alter_traveller_det_tr_phnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveller_det',
            name='tr_age',
            field=models.IntegerField(blank=True, default=0, verbose_name='tr_age'),
        ),
        migrations.AlterField(
            model_name='traveller_det',
            name='tr_phnum',
            field=models.IntegerField(blank=True, default=0, verbose_name='tr_phnum'),
        ),
    ]
